# Generated by Django 3.2.6 on 2021-10-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
