# Generated by Django 3.2.6 on 2021-10-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='button_value',
            field=models.CharField(default='Unfollow', max_length=8),
        ),
    ]
