# Generated by Django 3.2.6 on 2021-10-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_follow_button_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='button_value',
        ),
        migrations.AddField(
            model_name='followed',
            name='button_value',
            field=models.CharField(default='Unfollow', max_length=8),
        ),
    ]
